server:
  port: 8011

spring:
  application:
    name: zzeric-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: passwd
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 20
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池中的最小空闲连接
      min-idle: 5
      # 连接超时时间（毫秒）
      timeout: 0

#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 30 #心跳时间，即服务续约间隔时间(缺省30s)
#    lease-expiration-duration-in-seconds: 90 #没有心跳的淘汰时间，即服务续约到期时间(缺省90s)
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8011/eureka/
#
