server:
  port: 8035

spring:
  application:
    name: zzeric-eureka-consumer

eureka:
  instance:
    lease-expiration-duration-in-seconds: 90 #没有心跳的淘汰时间，即服务续约到期时间(缺省90s)
    lease-renewal-interval-in-seconds: 30 #心跳时间，即服务续约间隔时间(缺省30s)
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
    fetch-registry: true


# feign 全局配置
feign:
  client:
    config:
      default:
        connectionTimeOut: 5000   #请求连接的超时时间
        readTimeout: 1000  #请求处理的超时时间
  httpclient:
    enable: false
  okhttp:
    enable: true

#配置 ze
ribbon:
  ConnectionTimeout : 10
  ReadTimeOut : 10
  MaxAutoRetries : 1  #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer : 1 #要重试的下一个服务的最大数量 (不包含第一个服务)
  OkToRetryOnAllOperations : false


  #请求处理的超时时间


## feign 针对单个服务配置
#feign:
#  client:
#    config:
#      zeric-eureka-provider:  #微服务名称
#        connectionTimeOut: 3000  #请求连接的超时时间
#        readTimeout: 3000 #请求处理的超时时间
## feign底层默认使用jdk远程UrlConnection ,可以使用httpclient替换，okhttp替换
#  httpclient: #
#    enable: true
#  okhttp:
#    enable: false