server:
  port: 8090

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己(自己就是注册中心)
    fetch-registry: false   #false 不检索服务列表(注册中心自身不需要检测服务列表)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #测试环境关闭自我保护模式

spring:
  application:
    name: zzeric-eureka-server
  redis:
    # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: localhost
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 100
          # 连接池中的最小空闲连接
          min-idle: 5
          # 连接超时时间（毫秒）
          timeout: 0
