server:
  port: 8031

spring:
  application:
    name: zzeric-eureka-consumer

eureka:
  instance:
    hostname: euraka-consumer
    lease-expiration-duration-in-seconds: 90 #没有心跳的淘汰时间，即服务续约到期时间(缺省90s)
    lease-renewal-interval-in-seconds: 30 #心跳时间，即服务续约间隔时间(缺省30s)
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
